# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get tag name
      id: tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

    - name: Set up JDK11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: Run tests and linter
      env:
        TAG_NAME: ${{steps.tag_name.outputs.TAG_NAME}}
      run: ./gradlew check

    - name: Publish library
      if: github.ref == 'refs/heads/master'
      env:
        TAG_NAME: ${{steps.tag_name.outputs.TAG_NAME}}
        ORG_GRADLE_PROJECT_mavenUser: ${{secrets.MAVENUSER}}
        ORG_GRADLE_PROJECT_mavenPassword: ${{secrets.MAVENPASSWORD}}
        ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNINGKEY}}
        ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNINGPASSWORD}}
      run: ./gradlew publish
