name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: branch_name
      run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/tags/}

    - name: Set up JDK11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: Run tests and linter
      env:
        TAG_NAME: ${{steps.branch_name.outputs.BRANCH_NAME}}
      run: ./gradlew check
